config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  	resources :bids
  	resources :cars
  end
  
  resources :users 
  #resources :bids
  #resources :cars

  
  get 'users/:id/bids', to: 'users#view_bids', as: 'showBids'
  get 'users/:id/cars', to: 'users#view_cars', as: 'showCars'
  
  post 'cars/:id', to: 'cars#create_bid', as: 'createBid'
  
  root "cars#index"
  
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: %i[ show edit update destroy ]

  # GET /bids or /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1 or /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids or /bids.json
  def create
    @bid = Bid.new(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to bid_url(@bid), notice: "Bid was successfully created." }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1 or /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to bid_url(@bid), notice: "Bid was successfully updated." }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1 or /bids/1.json
  def destroy
    @bid.destroy

    respond_to do |format|
      format.html { redirect_to bids_url, notice: "Bid was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bid_params
      params.require(:bid).permit(:user_id, :car_id, :amount)
    end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_bid.html.erb
<div id="<%= dom_id bid %>">  

 <tr>
	<td class="align-middle text-center col-4"><h1><%= bid.user.name %></h1></td>
	<td class="align-middle text-center col-4">		
		<% if bid.user.avatar.attached? %>
			<%= image_tag url_for(bid.user.avatar), class: "img-thumbnail" %>
		<% else %>
			<%= image_tag bid.user.image, class: "img-thumbnail" %>
		<% end %>
	</td>
	<td class="align-middle text-center"><h1><%= bid.amount %> $</h1></td>
 </tr>

</div>

app/views/bids/_form.html.erb
<%= form_with(model: bid) do |form| %>
  <% if bid.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
        <% bid.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :car_id, style: "display: block" %>
    <%= form.text_field :car_id %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing bid</h1>

<%= render "form", bid: @bid %>

<br>

<div>
  <%= link_to "Show this bid", @bid %> |
  <%= link_to "Back to bids", bids_path %>
</div>

app/views/bids/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bids</h1>

<div id="bids">
  <% @bids.each do |bid| %>
    <%= render bid %>
    <p>
      <%= link_to "Show this bid", bid %>
    </p>
  <% end %>
</div>

<%= link_to "New bid", new_bid_path %>

app/views/bids/new.html.erb
<h1>New bid</h1>

<%= render "form", bid: @bid %>

<br>

<div>
  <%= link_to "Back to bids", bids_path %>
</div>

app/views/bids/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bid %>

<div>
  <%= link_to "Edit this bid", edit_bid_path(@bid) %> |
  <%= link_to "Back to bids", bids_path %>

  <%= button_to "Destroy this bid", @bid, method: :delete %>
</div>