config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  	resources :bids
  	resources :cars
  end
  
  resources :users 
  #resources :bids
  #resources :cars

  
  get 'users/:id/bids', to: 'users#view_bids', as: 'showBids'
  get 'users/:id/cars', to: 'users#view_cars', as: 'showCars'
  
  post 'cars/:id', to: 'cars#create_bid', as: 'createBid'
  
  root "cars#index"
  
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bid
  has_many :car
  has_one_attached :avatar
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @cars = Car.where(user_id: @user.id)
  end
  
  # GET /users/1/bids
  # Current user elotti implementacio
  def view_bids  	
  	@user = User.find(current_user.id) 
  	@bids = Bid.where(user_id: current_user.id)  
  end
  
  # GET /users/1/cars
  def view_cars
  	#p current_user.id
  	@user = User.find(current_user.id) 
  	@cars = Car.where(user_id: current_user.id)
  	
  	@carsArray = Hash.new(0)
  	
  	@cars.each do |car|
    		 hasBid = true
    		 if(Bid.where(car_id: car.id).empty?)
    		 	hasBid = false
    		 end
    		 @carsArray[car] = hasBid
    	end
  	  
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  	#@user.avatar.attach(params[:avatar])
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      	@user = User.find(current_user.id)
      	if @user.image.nil?
      		@user.image = "placeholder.jpeg"
      	end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :image, :avatar)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<br><br>

<div class="container">
    <div class="card text-center">
        <div class="card-header">
          <h1>Edit Profile</h1>
        </div>
        <div class="card-body">
            <br>
                
		<% if user.avatar.attached? %>
                	<%= image_tag url_for(user.avatar), class: "rounded-circle profile-picture-edit" %>
                <% else %>
                	<%= image_tag user.image, class: "rounded-circle profile-picture-edit" %>
                <% end %>
                
                <input id="profile-picture-upload" hidden="true" type="file">
                <div class="row justify-content-center">
                    <div class="col-4">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <%= form.label :name, class:"input-group-text" %>
                            </div>
                            <%= form.text_field :name, class:"form-control" %>
                        </div>
                    </div>
                    
                    <%= form.label :avatar  %>
                    <legend>Set Profile Picture</legend>
                    <%= form.file_field :avatar %>
                    
                </div>
          <%= form.submit class:"btn btn-primary" %>
        </div>
        <div class="card-footer">
        </div>
      </div>
</div>  
  
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  
	<div class="text-center">
		<b><h1><%= user.name %>'s Cars</h1></b>
		<!-- seed miatt -->
		<% if user.avatar.attached? %>
			<%= image_tag url_for(user.avatar), class: "user_carpage_profile-img" %>
		<% else %>
			<%= image_tag user.image, class: "user_carpage_profile-img" %>
		<% end %>
		
	</div>
	
	<div class="table-responsive"> 
      <div class="container container-border text-center">
          
          <!-- Top row -->
          <div class="row top-row row-border">
              	<div class="col-2">
            		<h2>Image</h2>
          	</div>
          	<div class="col-4">
			<h2>Car name</h2>
		</div>
		<div class="col-4">
			<h2>Current Price</h2>
		</div>
		<div class="col-2">
			&nbsp;
		</div>
          </div>

	<div id="cars">
		<% @cars.each do |car| %>
		    
			<div class="row row-border data-row">
				<div class="col-2 vert-center">
					<!-- seed miatt -->
					<% if car.picture.attached? %>
						<%= link_to image_tag(url_for(car.picture), class: "img-thumbnail top-space"), "#", data: {toggle: 'modal', target: '#Car'+car.id.to_s } %>
					<% else %>
						<%= link_to image_tag(car.image, class: "img-thumbnail top-space"), "#", data: {toggle: 'modal', target: '#Car'+car.id.to_s } %>		
					<% end %>
					
					
					
				</div>
				<div class="col-4 vert-center align-middle">
					<h2 class="data-column"><%= car.brand %> <%= car.model %></h2>
				</div>
				<div class="col-4 vert-center align-middle">
					<h2 class="data-column"><%= car.starting_price %>$</h2>
				</div>
				<div class="col-2 vert-center">
					<%= link_to "Bid", car, class: "btn btn-success btn-data-row" %>
				</div>
			</div>
			
			<div id="Car<%= car.id %>" class="modal fade" tabindex="-1" role="dialog">
				<div class="modal-dialog modal-width-fix">
					<div class="modal-content">
						<div class="modal-body">
						<!-- seed miatt -->
						<% if car.picture.attached? %>
							<%= image_tag url_for(car.picture), class: "img-fluid" %>
						<% else %>
							<%= image_tag car.image, class: "img-fluid" %>
						<% end %>
						</div>
					</div>
				</div>
			</div>
		    
  		<% end %>
	</div>

      </div>
    </div>	
	
</div>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

app/views/users/view_bids.html.erb
<br>
<center>
<div>
    <b><h1>My Bids</h1></b>
</div>
</center>
<br>

<div class="table-responsive">
	<div class="container container-border text-center">
    
	    <div class="row row-border top-row">
		<div class="col-3">
		    <h2>Image</h2>
		</div>
		<div class="col-3 ">
		    <h2>Car</h2>
		</div>
		<div class="col-3">
		    <h2>My bid</h2>
		</div>
		<div class="col-3">
		    <h2>Current bid</h2>
		</div>
	    </div>


		<div id="bids">
			<% @bids.each do |bid| %>
			    
			    <div class="row data-row">
				<div class="col-3 data-column">
				    
				    <% if bid.car.picture.attached? %>
					<%= image_tag url_for(bid.car.picture), class: "img-thumbnail" %>
				    <% else %>
					<%= image_tag bid.car.image, class: "img-thumbnail" %>		
				    <% end %>
				</div>
				<div class="col-3 data-column">
				    <%= link_to "#{bid.car.brand} #{bid.car.model}", bid.car, class: "dropdown-item" %>
				</div>
				<div class="col-3 data-column">
				    <div>
					<h2><%= bid.amount %>$</h2>
				    </div>
				</div>
				<div class="col-3 data-column">
				    <div>
					<h2><%= bid.car.starting_price %>$</h2>
				    </div>
				</div>
			    </div>
			    
			<% end %>
		</div>

    
	</div>
</div>

app/views/users/view_cars.html.erb
<div class="text-center">
  <!-- Title -->
  <br>
  <b><h1>My Cars</h1></b>
</div>

<br>

<div class="container container-border text-center">
  
  <!-- Top row -->
  <div class="row row-border top-row">
    <div class="col-3">
        <h2>Image</h2>
    </div>
    <div class="col-3 ">
        <h2>Carname</h2>
    </div>
    <div class="col-3">
      <h2>Current Price</h2>
    </div>
    <div class="col-1">
        &nbsp;
    </div>
  </div>

	<% @cars.each do |car| %>
		
	  <div class="row row-border data-row">
	    <div class="col-3 data-column">
		
		
		<% if car.picture.attached? %>
				<%= image_tag url_for(car.picture), class: "img-thumbnail top-space" %>
			<% else %>
				<%= image_tag car.image, class: "img-thumbnail top-space" %>		
			<% end %>
		
	    </div>
	    <div class="col-3 data-column">
		<h2><%= car.brand %> <%= car.model %>
		</h2>
	    </div>
	    <div class="col-3 data-column">
		<h2><%= car.starting_price %>$</h2>
	    </div>
	    <div class="col-3 data-column">
	      <% if not @carsArray[car] %>
	      <%= link_to "Edit", edit_car_path(car), class: "btn btn-info" %>
	      <%= button_to "Delete", car, method: :delete, class: "btn btn-danger top-space" %>
	      <% end %>
	    </div>
	  </div>	
		
	<% end %>

  
</div>