config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  	resources :bids
  	resources :cars
  end
  
  resources :users 
  #resources :bids
  #resources :cars

  
  get 'users/:id/bids', to: 'users#view_bids', as: 'showBids'
  get 'users/:id/cars', to: 'users#view_cars', as: 'showCars'
  
  post 'cars/:id', to: 'cars#create_bid', as: 'createBid'
  
  root "cars#index"
  
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_menu.html.erb
<%= stylesheet_link_tag "application.css" %>
<nav class="navbar navbar-expand-lg navbar-light navbar-blueish">
        <div class="container-fluid">
          <a class="navbar-brand" href="">Buy And Sell Cars </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Home", cars_path, class: "nav-link active" %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "My Cars", "/users/"+current_user.id.to_s+"/cars/", class: "dropdown-item" %>
		  <%= link_to "My Bids", "/users/"+current_user.id.to_s+"/bids/", class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Upload Car", new_car_path, class: "dropdown-item" %>
                  <%= link_to "Edit Profile", edit_user_path(1), class: "dropdown-item" %>
                </div>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Logout", destroy_user_session_path, :method =>  :delete%></li>
              
          </ul>
          </div>
        </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    
  </head>

  <body>
  
	<% if user_signed_in? %>
	  <%= render "layouts/menu"%>
	   
	<% end %>
  
 	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
  
	<%= yield %>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

  
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> 
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity= "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> 

    
  </body>
</html>